In [17]:
#pip install notebook
#jupyter install

In [18]:
import numpy as np

In [19]:
lst = [1,2,3,4,5]#1D array
print(lst)

[1, 2, 3, 4, 5]


In [20]:
print('1D array')
a = np.array([1,2,3,4,5])
print(a)


#-----------------------------------------------------------------------------


print('2D Array')
b = np.array([[1,2,3,4,5],
              [6,7,8,9,10]])
print(b)

#-----------------------------------------------------------------------------


print("3D Array")
c = np.array([[[1,2,3,4,5],
              [6,7,8,9,10],
             [11,12,13,14,15]]])
print(c)

1D array
[1 2 3 4 5]
2D Array
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
3D Array
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]


In [21]:
print(a.size)
print(b.size)
print(c.size)

5
10
15


In [22]:
print(a.shape)
print(b.shape)
print(c.shape)

(5,)
(2, 5)
(1, 3, 5)


In [23]:
d = np.array([[1,2,3,4.2,5],
            [6,7,8.9,9,10],
            [11,12,13,14,15]])
print(d.dtype) #getting data type

float64


In [24]:
#transpose matrix
#addition of 2 2D matrix

In [ ]:
#transpose matrix(task 1)
e = np.array([[1,2,3],
            [6,7,8],
            [11,12,13]])

e_transpose = e.transpose()
print(e_transpose)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]]


In [ ]:
#how to add matrix(task 1)
x = np.array([1,2,3])
y = np.array([1,2,3])
sum = x + y
print(sum)

[2 4 6]


In [30]:
x = np.ones((6),dtype=int)
x

array([1, 1, 1, 1, 1, 1])

In [31]:
z = np.zeros((4,8),dtype=int)
z

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [34]:
a = np.arange(1,21) #1 - 20 sorted data list 
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [36]:
#print only the sorted odd numbers

b = np.arange(1,21,2)
print(b)

#print only the sorted even numbers
c = np.arange(2,21,2)
c

[ 1  3  5  7  9 11 13 15 17 19]


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [44]:
b = b.reshape(2,5)
print(b)

print()

c= c.reshape(2,5)
print(c)

[[ 1  3  5  7  9]
 [11 13 15 17 19]]

[[ 2  4  6  8 10]
 [12 14 16 18 20]]


In [46]:
a = np.arange(0,18)
a = a.reshape(6,3)

b = np.arange(20,38)
b = b.reshape(6,3)

c = a+b

print(c)

[[20 22 24]
 [26 28 30]
 [32 34 36]
 [38 40 42]
 [44 46 48]
 [50 52 54]]
